name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post deployment status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.https://discord.com/api/webhooks/1419059622811271308/8RJjtnT2ARdeNSoNuHxxiW5e5_eFhGRoTZv3nOtYBDuCmByGmjY9GSHNz8siOl1JkGFf }}